# fly.toml app configuration file generated for back-red-leaf-1146 on 2024-06-27T11:06:07+09:00
app = "back-red-leaf-1146"
primary_region = "nrt"

[build]
  dockerfile = "./Dockerfile"

[env]
  RAILS_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false 
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
